/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.function.Function;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class DuckDuckGoSearchTest {

    private static WebDriver driver;
    private static DuckDuckGoProxy proxy;

    @BeforeClass
    public static void setUp() {
        driver = new WebDriverFactory().create();
        proxy = new DuckDuckGoProxy(driver);
        proxy.start();
    }

    @AfterClass
    public static void tearDown() {
        driver.quit();
    }

    @Test
    public void titleIsDuckDuckGo() {
        assertTrue(driver.getTitle().startsWith("DuckDuckGo"));
    }

    @Test
    public void searchIsWorking() {
        proxy.submitSearch("seleniumhq");
        assertTrue(waitUtil(10, d -> d.getTitle().startsWith("seleniumhq")));
        assertEquals("seleniumhq at DuckDuckGo", driver.getTitle());
    }

    private static <V> V waitUtil(long timeOutInSeconds, Function<? super WebDriver, V> isTrue) {
        return new WebDriverWait(driver, timeOutInSeconds).until(isTrue);
    }
}
